// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmnpovghqaayjgdllhvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tbnBvdmdocWFheWpnZGxsaHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTIxMjYsImV4cCI6MjA3Mjg4ODEyNn0.P1UNCtq9ePnc3KGCe9BuuN9ueHkw_lEOl40X0VTlp4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});